[color-theme]
name = "moonlike"

[ui]
drop-shadow-width = 0

[color-theme.base]
white = "#A4AED4"
black = "#FFFFFF"
grey = "#000000"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#FCC152"
orange = "#FF5370"
green = "#B4E970"
purple = "#C678DD"
cyan = "#51E2FD"
magenta = "#C678DD"

[color-theme.syntax]
"attribute" = "$yellow"
"boolean" = "#569cd6"
"builtinType" = "$cyan"
"character" = "$purple"
"comment" = "#7e8eda"
"conditional" = "$blue"
"constant" = "#d4d4d4"
"constructor" = "#4fc1ff"
"embedded" = "$cyan"
"enum" = "#4ec9b0"
"enum-member" = "#4fc1ff"
"enumMember" = "#4fc1ff"
"escape" = "$cyan"
"string.escape" = "#FF5370"
"exception" = "$red"
"field" = "$red"
"float" = "$yellow"
"function" = "#5773C0"
"function.method" = "#5773C0"
"include" = "#51E6FE"
"interface" = "#4ec9b0"
"keyword" = "#569cd6"
"method" = "#5773C0"
"number" = "#b5cea8"
"property" = "#9cdcfe"
"punctuation.bracket" = "$yellow"
"punctuation.delimiter" = "#d4d4d4"
"repeat" = "$green"
"selfKeyword" = "#569cd6"
"string" = "#ce9178"
"struct" = "$yellow"
"structure" = "$yellow"
"symbol" = "$yellow"
"type" = "#8F6BBB"
"variable" = "#e4f3fa"
"type.builtin" = "$cyan"
"typeAlias" = "#4ec9b0"
"variable.other.member" = "$red"
"text.title" = "$orange"
"text.uri" = "$cyan"
"text.reference" = "$yellow"
"tag" = "$blue"

[color-theme.ui]
"activity.background" = "#222539"
"activity.current" = "#5865f2"

"completion.background" = "#2f3136"
"completion.current" = "#292b2f"
 
"editor.background" = "#222539"
"editor.caret" = "#76688B"
"editor.current_line" = "#343653"
"editor.dim" = "#7e8eda"
"editor.focus" = "#ddddee"
"editor.foreground" = "#d4d4d4"
"editor.link" = "$cyan"
"editor.selection" = "#343653"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#d7d8d922"
"editor.drag_drop_tab_background" = "#d7d8d922"

"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"

"hover.background" = "#2f3136"

"inlay_hint.background" = "#40444b"
"inlay_hint.foreground" = "#c9cbce"

"lapce.border" = "#21243B"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.scroll_bar" = "#343653"
"lapce.warn" = "$yellow"

"lapce.button.primary.background" = "#222539"
"lapce.button.primary.foreground" = "$white"


"lapce.tab.active.background" = "#222539"
"lapce.tab.active.foreground" = "#c0c7d6"
"lapce.tab.active.underline" = "#343653"

"lapce.tab.inactive.background" = "#1E2032"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#36393f"

"lapce.tab.separator" = "#343653"

"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#3E68D7"

"lapce.remote.local" = "#3E68D7"
"lapce.remote.connected" = "#1E2032"
"lapce.remote.connecting" = "#1E2032"
"lapce.remote.disconnected" = "#3E68D7"

"lapce.plugin.name" = "#C4D2FA"
"lapce.plugin.description" = "$white"
"lapce.plugin.author" = "#3E68D7"

"markdown.blockquote" = "#898989"

"palette.current" = "#1E2032"
"palette.background" = "#1E2032"
"palette.foreground" = "$white"
"palette.current.background" = "#36393f"
"palette.current.foreground" = "$white"

"panel.background" = "#1E2032"
"panel.current" = "#282D4A"
"panel.hovered" = "#282D4A"

"source_control.added" = "#1E2032"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"

"status.background" = "#1E2032"
"status.foreground" = "#6273AE"
"status.modal.insert" = "$red"
"status.modal.normal" = "#3E68D7"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"

"terminal.background" = "#222539"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"
